name: Merge into develop

on:
  push:
    branches: [ develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-distribute:
    name: Build and distribute
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b #v4.1.5
        with:
          fetch-depth: '0'

      - name: Setup JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 #4.2.1
        with:
          java-version: 17
          distribution: oracle

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@00854ea68c109d98c75d956347303bf7c45b0277 #v3.2.1

      - name: Generate release notes
        run: git log --format=%B -n 1 > releasenotes.txt

      - name: Build APK and distribute to firebase
        run: ./gradlew assembleAlpha appDistributionAlpha
        env:
          CI_ACCESS_USERNAME: ${{ secrets.CI_ACCESS_USERNAME }}
          CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}