name: Pull Request

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ develop, main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets:
      CI_ACCESS_USERNAME: ${{ secrets.CI_ACCESS_USERNAME }}
      CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
  unit-test:
    uses: ./.github/workflows/unit_test.yml
    secrets:
      CI_ACCESS_USERNAME: ${{ secrets.CI_ACCESS_USERNAME }}
      CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
  sonar-scanner:
    uses: ./.github/workflows/sonar_scanner.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI_ACCESS_USERNAME: ${{ secrets.CI_ACCESS_USERNAME }}
      CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
