name: SonarCloud scanner

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: 'A token to be used to send sonar scan results'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-sonar
  cancel-in-progress: true

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b #v4.1.5
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@2.3.0 # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/sonarcloud-scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
